### ISSUE TITLE
managing teams in probot/settings results in a 404 for a GHE instance

### ISSUE THREAD

**Issue by travi** [octokit/plugin-enterprise-compatibility.js#60]
Just capturing this since it doesn't appear to be handled yet, according to https://github.com/probot/settings/issues/235

**Comment by gr2m** [comment]
@travi and I plan on pairing on this today :)

**Comment by gr2m** [comment]
Here is our current plan

1. Check if a request path matches `/orgs/*/teams`
2. Send the request as is
3. Catch the error
4. If `error.status` is `404` and response headers indicated a GitHub Enterprise version, then throw a helpful error to e.g. `octokit.teams.addOrUpdateRepoInOrg(options) is not supported in your GitHub Enterprise Server version. Please replace the method with octokit.request('PUT /teams/:team_id/repos/:owner/:repo, options')`
